"""Auto-recorded macro - generated by element_finder.py's record mode
on 2026-08-24 19:22:18.

Recorded 3 click(s) in a window matching WINDOW_TITLE_RE. NOT
reviewed yet - check before wiring to a hotkey in run.py:

- Steps using automation.click_element(...) had a title/auto_id at record
  time and go through the same UIA-first, coords-fallback path every other
  macro in this project uses.
- Steps calling pyautogui.click(x, y) directly are COORDINATE-ONLY: the
  clicked element had no title/auto_id at record time (a generic
  Pane/View-style control), so no UIA criteria was safe to guess without
  risking a match on the wrong same-class element elsewhere in the tree.
  These WILL break if the window moves, resizes, or renders at a different
  DPI/resolution. Re-derive real criteria with element_finder.py (hover + P
  for the ancestor chain) before trusting this macro.
  Coordinate-only steps: [3]

WINDOW_TITLE_RE was derived from the exact window title captured at record
time - if this app's title includes dynamic content (unread counts,
filenames, unsaved-change markers), trim it to a stable substring yourself,
the same way other macros/*.py files do, rather than trusting an exact
match long-term.

Not handled by the recorder - re-record or hand-edit if any step needed one
of these: right-clicks, double-clicks, drags. A double-click records as two
close-together single clicks, which may not register as a real double-click
to apps that check OS double-click timing. A drag records as a single click
at its start point only - the drag's endpoint/motion is silently lost.

Inter-step sleeps are capped at 3.0s even if the original pause
was longer (see each step's comment for the raw recorded gap) - restore a
longer sleep by hand if the target app genuinely needs more time to respond.
"""

import time

import automation
import pyautogui

WINDOW_TITLE_RE = '.*Taskbar.*'


def replay():
    window = automation.focus_window(WINDOW_TITLE_RE)

    # Step 1: title="Visual Studio Code - 1 running window pinned" control_type="Button" auto_id="Appid: Microsoft.VisualStudioCode" class_name="Taskbar.TaskListButtonAutomationPeer" (x=314, y=1414)
    automation.click_element(window, {'control_type': 'Button', 'title': 'Visual Studio Code - 1 running window pinned', 'auto_id': 'Appid: Microsoft.VisualStudioCode'}, coords=(314, 1414))

    time.sleep(1.295)  # raw recorded gap: 1.295s
    # Step 2: title="Visual Studio Code - 1 running window pinned" control_type="Button" auto_id="Appid: Microsoft.VisualStudioCode" class_name="Taskbar.TaskListButtonAutomationPeer" (x=315, y=1408)
    automation.click_element(window, {'control_type': 'Button', 'title': 'Visual Studio Code - 1 running window pinned', 'auto_id': 'Appid: Microsoft.VisualStudioCode'}, coords=(315, 1408))

    window = automation.focus_window('.*Agents.*')
    time.sleep(2.717)  # raw recorded gap: 2.717s
    # Step 3: COORDINATE-ONLY - no title/auto_id at record time
    # captured element: control_type="Pane" class_name="View" (x=93, y=888)
    pyautogui.click(93, 888)
